CREATE SCHEMA IF NOT EXISTS wanikani;

CREATE TABLE IF NOT EXISTS cards
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL,
    familiarity integer,
    interval_hours integer,
    kanji_id bigint,
    last_reviewed timestamp(6) with time zone,
    next_due timestamp(6) with time zone,
    user_id bigint,
    CONSTRAINT cards_pkey PRIMARY KEY (id),
    CONSTRAINT cards_uuid_uq UNIQUE (uuid),
    CONSTRAINT cards_userid_fk FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT cards_kanjiid_fk FOREIGN KEY (kanji_id)
        REFERENCES wanikani.kanji (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
